---
# Variables that will be passed are below.
#   flavor: Parameters of flavor

- name: "Declare parameters_of_flavor. [flavor={{ flavor }}]"
  set_fact:
    parameters_of_flavor: "{{ flavor | combine({\"state\": \"present\"}) }}"

- name: "Add a flavor. [parameters -> {{ parameters_of_flavor }}]"
  openstack.cloud.compute_flavor: "{{ parameters_of_flavor }}"

