---
- name: "Common roles to deploy servers"
  hosts: all
  become: yes
  roles:
    - { role: image, tags: ['role_image']}
    - { role: flavor, tags: ['role_flavor']}
    - { role: ssh_key, tags: ['role_ssh_key']}
    - { role: security_groups, tags: ['role_security_groups']}
    - { role: server, tags: ['role_server']}
  vars_files:
    - "external_vars/ssh_public_keys.yml"
