---
- name: "Common roles to deploy servers"
  hosts: all
  become: yes
  roles:
    - { role: image, tags: ['role_image']}
    - { role: network, tags: ['role_network']}
    - { role: subnet, tags: ['role_subnet']}
    - { role: router, tags: ['role_router']}
    - { role: rbac, tags: ['role_rbac']}
    - { role: flavor, tags: ['role_flavor']}
    - { role: ssh_key, tags: ['role_ssh_key']}
    - { role: security_groups, tags: ['role_security_groups']}
    - { role: server, tags: ['role_server']}

  environment:
    OS_USERNAME: "{{ group_vars.openstack.auth.env.OS_USERNAME }}"
    OS_PASSWORD: "{{ group_vars.openstack.auth.env.OS_PASSWORD }}"
    OS_PROJECT_NAME: "{{ group_vars.openstack.auth.env.OS_PROJECT_NAME }}"
    OS_USER_DOMAIN_NAME: "{{ group_vars.openstack.auth.env.OS_USER_DOMAIN_NAME }}"
    OS_PROJECT_DOMAIN_NAME: "{{ group_vars.openstack.auth.env.OS_PROJECT_DOMAIN_NAME }}"
    OS_AUTH_URL: "{{ group_vars.openstack.auth.env.OS_AUTH_URL }}"
    OS_IDENTITY_API_VERSION: "{{ group_vars.openstack.auth.env.OS_IDENTITY_API_VERSION }}"

  vars_files:
    - "external_vars/ssh_public_keys.yml"
