---
- name: Create a new instance with
  openstack.cloud.server:
    state: present
    name: "{{ server.name }}"
    image: "{{ server.image }}"
    key_name: "{{ server.ssh_public_key_pair_name }}"
    auth:
        auth_url: http://dev-controller01:5000
        username: admin
        password: goi_su_maguro7
        project_name: admin
        user_domain_name: Default
        project_domain_name: Default

    #auth: "{{ auth_parameters }}"
    # A format of a key 'nics: "{{ server.nics }}"' is equivarent to...
    #   nics:
    #     - net-name: network_name
    #       nics:
    #         - net-id: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    #         - net-name: name_of_network
    #nics: "{{ server.nics }}"
    nics:
      - net-name: private
    timeout: "{{ server.timeout }}"
    flavor: "{{ server.flavor }}"
    # A format of a key 'security_groups: "{{ server.security_groups }}"' is equivarent to...
    #   security_groups:
    security_groups: "{{ server.security_groups }}"

