---
- name: Create a new instance with
  openstack.cloud.server:
    state: present
    name: "{{ server.name }}"
    image: "{{ server.image }}"
    auth: "{{ auth_parameters }}"
    # A format of a key 'nics: "{{ server.nics }}"' is equivarent to...
    #   nics:
    #     - net-name: network_name
    #       nics:
    #         - net-id: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    #         - net-name: name_of_network
    nics: "{{ server.nics }}"
    timeout: "{{ server.timeout }}"
    flavor: "{{ server.flavor }}"
    # A format of a key 'security_groups: "{{ server.security_groups }}"' is equivarent to...
    #   security_groups:
    security_groups: "{{ server.security_groups }}"

