---
# A task is to create a server
#
# An expected variable to be passed are below.
#   server:
#     A variable of dictionary of the server that will be created.
#

# Due custome parameters

- name: "Declare option-nics to use it when \"openstack create server\""
  set_fact:
    - option-nics: []

- name: Print a server that will be created
  ansible.builtin.debug:
    msg: "server.name={{ server.name }}, server.image={{ server.image }}, {% if 'key_name' in server %}server.key_name={{ server.key_name }}{% endif %}, server.nics={{ server.nics }}"

- name: "Create a new instance ({{ server }})"
  openstack.cloud.server: "{{ server }}"

## FIXME: Creating a server like below is not a flexible way.
#- name: Include do_create_server.yml if you did not declare key_name(key name of ssh)
#  include_tasks: do_create_server.yml
#  when: "'key_name' not in server"
#
#- name: Include do_create_server_with_ssh_public_key_pair.yml if you declared key_name(key name of ssh)
#  include_tasks: do_create_server_with_ssh_public_key_pair.yml
#  when: "'key_name' in server"

