---
# A task is to create a server
#
# An expected variable to be passed are below.
#   server:
#     A variable of dictionary of the server that will be created.
#   server.auth_url (optional):
#     An auth URL to create the server.

- name: Print a server will be created
  ansible.builtin.debug:
    msg: "server.name={{ server.name }}, server.image={{ server.image }}, {% if 'ssh_public_key_pair_name' in server %}server.key_name={{ server.ssh_public_key_pair_name }}{% endif %}, server.auth.auth_url={{ server.auth.auth_url }}, server.auth.username={{ server.auth.username }}, server.auth.project_name={{ server.auth.project_name }}, server.auth.user_domain_name={{ server.auth.user_domain_name }}, server.auth.project_domain_name={{ server.auth.project_domain_name }}, server.nics."

  # FIXME: Creating a server like below is not a flexible way.
- name: Include do_create_server.yml if you did not declare ssh_public_key_pair_name
  include: do_create_server.yml
  when: "'ssh_public_key_pair_name' not in server"

- name: Include do_create_server_with_ssh_public_key_pair.yml if you declared ssh_public_key_pair_name
  include: do_create_server_with_ssh_public_key_pair.yml
  when: "'ssh_public_key_pair_name' in server"

