---
- name: "Include prepare_port/main.yml"
  include_tasks: prepare_port/main.yml
  loop_control:
    loop_var: port
  loop: "{{ group_vars.openstack.ports }}"
  when: "('ports' in group_vars.openstack)"

