---

# FIXME: Parameters of auth should be declared in environment variables to be able to additional codes to declare auth parameters.
#
- name: "Declare auth_parameters for default"
  set_fact:
    auth_parameters: "{{ group_vars.openstack.auth.default }}"

- name: "Declare key and value of ssh public key"
  set_fact:
    ssh_key_name: "{{ ssh_key.key }}"
    ssh_key_value: "{{ ssh_key.value.value }}"

- name: Print ssh_key_name and ssh_key_value that will be registard
  ansible.builtin.debug:
    msg: "ssh_key_name={{ ssh_key_name }}, ssh_key_value={{ ssh_key_value }}"

- name: Add public key to the OpenStack
  openstack.cloud.keypair:
    auth: "{{ auth_parameters }}"
    state: present
    name: "{{ ssh_key_name }}"
    public_key: "{{ ssh_key_value }}"

