---
- name: "Declare key and value of ssh public key"
  set_fact:
    ssh_key_name: "{{ ssh_key.key }}"
    ssh_key_value: "{{ ssh_key.value.value }}"

- name: "Add public key to the OpenStack. ssh_key_name={{ ssh_key_name }}, public_key={{ ssh_key_value }}"
  openstack.cloud.keypair:
    state: present
    name: "{{ ssh_key_name }}"
    public_key: "{{ ssh_key_value }}"

