---
# Variables are below.
# rbac: RBAC object that contains 'network_name', 'project_name', args that

# TODO: It will be replaced to environment variable.
- name: "Declare auth_parameters if \"auth_ref\" is existed at (group_vars.openstack.servers.[].name == {{ server.name }})"
  set_fact:
    auth_parameters: "{{ group_vars.openstack.auth['default'] }}"

# type of RBAC ---------------------------------------------------------------------------------------------------------------------------------------------------------
- name: "Declare type of RBAC as default if it was not specified"
  set_fact:
    rbac_type: "network"
  when: "'type' not in rbac"

- name: "Declare type of RBAC"
  set_fact:
    rbac_type: "{{ rbac.type }}"
  when: "'type' in rbac"

# object_id of RBAC ---------------------------------------------------------------------------------------------------------------------------------------------------------
- name: "Declare object_id of RBAC"
  set_fact:
    rbac_object_id: "{{ rbac.object_id }}"

# domain of RBAC ---------------------------------------------------------------------------------------------------------------------------------------------------------
- name: "Declare domain of RBAC"
  set_fact:
    rbac_domain: "{{ rbac.domain }}"

# target_project_id of RBAC ------------------------------------------------------------------------------------------------------------------------------------------------
- name: "Declare target_project_id of RBAC"
  set_fact:
    rbac_target_project_id: "{{ rbac.target_project_id }}"

# action of RBAC ----------------------------------------------------------------------------------------------------------------------------------------------------------
- name: "Declare action of RBAC as default if it was not specified"
  set_fact:
    rbac_action: "access_as_external"
  when: "'type' not in rbac"

- name: "Declare action of RBAC"
  set_fact:
    rbac_action: "{{ rbac.action }}"

# TODO: Create RBAC
