---
# Parameters that will be passed are below.
#   external_network_list: Name of networks as external.
#   subnet: A subnet that will be added in the network.

- name: Include create_subnet_for_external_network/main.yml
  include_tasks: create_subnet_for_external_network/main.yml
  when: "subnet.network_name in external_network_list"

- name: Include create_subnet_for_internal_network/main.yml
  include_tasks: create_subnet_for_internal_network/main.yml
  when: "subnet.network_name not in external_network_list"

