---
# Parameters that will be passed are below.
#   external_network_list: Name of networks as external.
#   subnet: A subnet that will be added in the network.

- name: "Print a subnet that will be created"
  ansible.builtin.debug:
    msg: "This is a task to create a subnet. [subnet={{ subnet }}, external_network_list={{ external_network_list }}]"

- name: "Declare parameters_of_subnet to create a subnet"
  set_fact:
    parameters_of_subnet: "{{ subnet | combine({\"state\": \"present\"}) }}"

- name: Create subnet for external network
  openstack.cloud.subnet: "{{ parameters_of_subnet }}"

