---
- name: Create a list of network that specified as external
  set_fact:
    external_network_list: "[{% for item in group_vars.openstack.networks if 'external' in item and item.external == True %}'{{ item.name }}'{% if not loop.last %},{% endif %}{% endfor %}]"

- name: Print external networks
  ansible.builtin.debug:
    msg: "external_network_list={{ external_network_list }}"

- name: Include create_subnet.yml
  include_tasks: create_subnet.yml
  loop_control:
    loop_var: subnet
  loop: "{{ group_vars.openstack.subnets }}"

# TODO: Project "admin" should be replaced by variable
- name: Show list of network subnets
  openstack.cloud.subnets_info:
    project_name: admin
  register: subnet_info

- name: "Show subnets"
  ansible.builtin.debug:
    msg: "{{ subnet_info }}"

