---
# Variables that will be passed are below.
#   security_group: Parameters of security group that will be created.
#   project_name: A name of the project that the security group will be created.
#   security_group_rule: A rule that will be added in the security_group

- name: Declare parameters_of_securigy_group_rule
  set_fact:
    parameters_of_security_group_rule: "{{ security_group_rule }}"

- name: Declare a name in parameters_of_security_group_rule
  set_fact:
    parameters_of_security_group_rule: "{{ parameters_of_security_group_rule | combine({\"security_group\": security_group.name}) }}"

- name: Declare a project in parameters_of_security_group_rule
  set_fact:
    parameters_of_security_group_rule: "{{ parameters_of_security_group_rule | combine({\"project\": project_name}) }}"

- name: "Print a security group rule that will be created"
  ansible.builtin.debug:
    msg: "security_group.name -> {{ security_group.name }}, project -> {{ project_name }}, rule -> {{ security_group_rule }}"

# Creating security group by using openstack.cloud.security_group_rule module.
# For mor details, please refer "https://docs.ansible.com/ansible/latest/collections/openstack/cloud/security_group_rule_module.html#ansible-collections-openstack-cloud-security-group-rule-module".
- name: "Create a security group rule"
  openstack.cloud.security_group_rule: "{{ parameters_of_security_group_rule }}"

