---
# Variables that will be passed are below.
#   security_group: Parameters of security group that will be created.
- name: "Include create_security_group.yml"
  include_tasks: create_security_group.yml
  loop_control:
    loop_var: project_name
  loop: "{{ security_group.projects }}"

