---
# Variables that will be passed are below.
#   

- name: "Declare description of a security group \"{{ group_vars.openstack.security_groups }}\""
  set_fact:
    description_of_security_group: "{% if 'description' in security_group %}{{ security_group.description }}{% else %}{% endif %}"

- name: "Create security group \"{{ group_vars.openstack.security_groups }}\""
  openstack.cloud.security_group:
    name: "{{ group_vars.openstack.security_groups }}"
    cloud: mordred
    state: present
    description: "{{ description_of_security_group }}"

# TODO: Add group rules

