---
# Variables that will be passed are below.
#   security_group: Parameters of security group that will be created.

- name: "Declare description of a security group \"{{ group_vars.openstack.security_groups }}\""
  set_fact:
    description_of_security_group: "{% if 'description' in security_group %}{{ security_group.description }}{% else %}{% endif %}"

# FIXME: Parameters of auth should be declared in environment variables to be able to additional codes to declare auth parameters.
- name: "Declare auth_parameters for default"
  set_fact:
    auth_parameters: "{{ group_vars.openstack.auth.default }}"

- name: "Create a security group \"{{ group_vars.openstack.security_groups }}\""
  openstack.cloud.security_group:
    name: "{{ security_group.name }}"
    auth: "{{ auth_parameters }}"
    state: present
    description: "{{ description_of_security_group }}"

# TODO: Add group rules
- name: "Include create_security_group_rule.yml"
  include_tasks: create_security_group_rule.yml
    loop_var: security_group_rule
  loop: "{{ security_group.rules }}"

