---
# A role to create servers on OpenStack

- name: Include create_server/main.yml
  include_tasks: create_server/main.yml
  loop_control:
    loop_var: server
  loop: "{{ group_vars.openstack.servers }}"
