---
- name: "Include create_router/main.yml"
  include_tasks: create_router/main.yml
  loop_control:
    loop_var: router
  loop: "{{ group_vars.openstack.routers }}"

# TODO: Project "admin" should be replaced by variable
- name: "Register a variable of routers"
  openstack.cloud.router_info:
    project_name: admin
  register: router_info

- name: "Show routers"
  ansible.builtin.debug:
    msg: "{{ router_info }}"
